name: synchronized_call

version: 1.0.8

description: Lock mechanism to prevent concurrent access to asynchronous code.

homepage: https://github.com/isaacselement/synchronized_call.dart

repository: https://github.com/isaacselement/synchronized_call.dart

environment:
  sdk: '>=2.12.2 <3.0.0'


dev_dependencies:
  lints:
  test:
